#!/bin/sh
# deploy/partition.sh — filesystem creation and Btrfs subvolume layout.

# Format a partition with the selected filesystem
partition_format() {
    _dev="$1"
    _fs="$2"
    _label="${3:-omni-root}"

    deploy_confirm "This will ERASE ALL DATA on /dev/$_dev. Format as $_fs?" || return 1

    case "$_fs" in
        ext4)
            mkfs.ext4 -L "$_label" -F "/dev/$_dev"
            ;;
        btrfs)
            mkfs.btrfs -L "$_label" -f "/dev/$_dev"
            ;;
        xfs)
            mkfs.xfs -L "$_label" -f "/dev/$_dev"
            ;;
        f2fs)
            mkfs.f2fs -l "$_label" -f "/dev/$_dev"
            ;;
        *)
            log_error "unsupported filesystem: $_fs"
            return 1
            ;;
    esac
}

# Create standard Btrfs subvolume layout
partition_btrfs_subvols() {
    _dev="$1"
    _mnt="${2:-$DEPLOY_TARGET}"

    mount "/dev/$_dev" "$_mnt" || { log_error "cannot mount /dev/$_dev"; return 1; }

    log_info "Creating Btrfs subvolumes..."
    btrfs subvolume create "$_mnt/@"          || { log_error "failed: @"; return 1; }
    btrfs subvolume create "$_mnt/@home"      || { log_error "failed: @home"; return 1; }
    btrfs subvolume create "$_mnt/@snapshots"  || { log_error "failed: @snapshots"; return 1; }
    btrfs subvolume create "$_mnt/@var_log"    || { log_error "failed: @var_log"; return 1; }

    umount "$_mnt"

    # Remount with @ as root subvolume
    mount -o subvol=@,noatime,compress=zstd:1,discard=async,space_cache=v2 "/dev/$_dev" "$_mnt"
    mkdir -p "$_mnt/home" "$_mnt/.snapshots" "$_mnt/var/log"
    mount -o subvol=@home,noatime,compress=zstd:1        "/dev/$_dev" "$_mnt/home"
    mount -o subvol=@snapshots,noatime                   "/dev/$_dev" "$_mnt/.snapshots"
    mount -o subvol=@var_log,noatime,compress=zstd:1     "/dev/$_dev" "$_mnt/var/log"

    log_info "Btrfs subvolumes created and mounted at $_mnt"
}

# Generate fstab entries for the target
partition_generate_fstab() {
    _dev="$1"
    _fs="$2"
    _target="${3:-$DEPLOY_TARGET}"
    _uuid=$(blkid -s UUID -o value "/dev/$_dev" 2>/dev/null)

    [ -z "$_uuid" ] && { log_error "cannot read UUID for /dev/$_dev"; return 1; }

    mkdir -p "$_target/etc"

    if [ "$_fs" = "btrfs" ]; then
        cat > "$_target/etc/fstab" << FSTAB
# Generated by Universal Omni-Master
UUID=$_uuid /            btrfs  defaults,noatime,compress=zstd:1,discard=async,space_cache=v2,subvol=@ 0 0
UUID=$_uuid /home        btrfs  defaults,noatime,compress=zstd:1,discard=async,space_cache=v2,subvol=@home 0 0
UUID=$_uuid /.snapshots  btrfs  defaults,noatime,subvol=@snapshots 0 0
UUID=$_uuid /var/log     btrfs  defaults,noatime,compress=zstd:1,subvol=@var_log 0 0
FSTAB
    else
        cat > "$_target/etc/fstab" << FSTAB
# Generated by Universal Omni-Master
UUID=$_uuid /  $_fs  defaults,noatime 0 1
FSTAB
    fi

    log_info "fstab generated at $_target/etc/fstab"
}
